# Generated by Django 3.2.16 on 2022-12-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_buyer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpaymentschedule',
            name='is_notification_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
