# Generated by Django 3.2.16 on 2022-11-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_buyer_buyerpaymentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpaymentschedule',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerpaymentschedule',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
