# Generated by Django 3.2.16 on 2022-11-25 06:23

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221123_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
