# Generated by Django 3.2.16 on 2022-11-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_property_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyVideo',
        ),
    ]
