# Generated by Django 3.2.16 on 2022-11-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221125_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='city',
            new_name='address',
        ),
    ]
