# Generated by Django 3.2.16 on 2022-11-23 06:59

from django.db import migrations
import phison_realestate_backend.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', phison_realestate_backend.users.managers.UserManager()),
            ],
        ),
    ]
